// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pifcxslklkfqprhxkpnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZmN4c2xrbGtmcXByaHhrcG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNDA2NDYsImV4cCI6MjA1NDkxNjY0Nn0.e1hNFm9BTKA1oHaUCuO5Ol1qXXmTb3HzMQzsuHaHTNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);